require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - vendor/ruby/**/*
    - node_modules/**/*
    - .licenses/**/*
    - db/migrate/**
    - db/seeds.rb
    - lib/devise/models/validatable.rb
Rails:
  Enabled: true
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
Metrics/AbcSize:
  Exclude:
    - app/controllers/admin/managers/sessions_controller.rb
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - db/migrate/*
    - config/environments/*
    - lib/tasks/**/*
    - spec/**/*
    - config/routes.rb
Metrics/ParameterLists:
  CountKeywordArgs: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/HashSyntax:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
